# Strings
title: Nándor Szalma's website
baseurl: "https://nandee95.github.io"
introduction: "Software developer"

# Details
fullname: Nándor Szalma
profession: Software Engineer

# Social
twitter: nandee95
github: nandee95
gitlab: nandee95
stackoverflow : 7788244/nandee
disqus: nandee95
linkedin: nandor-szalma
# thingiverse: nandee95

# Markdown settings
highlighter: rouge
#markdown: redcarpet
#redcarpet:
#  extensions: [tables]

# Time settings
timezone: Europe/Budapest
