title: Nándor Szalma's website
fullname: Nándor Szalma
profession: Programmer
email: n.a.
description: Nándor Szalma's blog
baseurl: ""
url: ""
twitter_username: nandee95
github_username:  nandee95
disqus: nndorszalma

markdown: kramdown